version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - voice-biomarker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Local PostgreSQL for development (optional)
  postgres-dev:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: voice_biomarker_users_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voice-biomarker-network
    profiles:
      - dev

networks:
  voice-biomarker-network:
    driver: bridge

volumes:
  postgres_data: